---
Name: IGF
---
Director:
  rules:
    'session//$ID!/$Action': 'SessionController',
    'meeting//$ID!/$Action': 'MeetingController',
    'transcript//$ID!': 'TranscriptController',
    'item//$ID!': 'LinkItemController',
    'proposal//$ID!': 'ProposalController'
