---
Name: IGF
---
Director:
  rules:
    'session//$ID!/$Action': 'SessionController',
    'Meeting//$ID!/$Action': 'MeetingController',
    'transcript//$ID!': 'TranscriptController',
    'item//$ID!': 'LinkItemController',
    'proposal//$ID!': 'ProposalController',
    'report//$ID!': 'ReportController',
    'regional//$ID': 'RegionalNationalController'
SolrCellTextExtractor:
  base_url: 'http://localhost:8983/solr/MyIndex/update/extract'