<?php

class MeetingSessionImporter extends CsvBulkLoader{
	
	// public $columnMap = array(
	// 	'Title' => 'Title', 
	// 	'Date' => 'Date', 
	// 	'Type' => 'Type.', //Relation title
	// 	'Topic' => 'Topic.', //Relation title
	// 	'Meeting' => 'Meeting.', //Relation title
	// 	'Content' => 'Content',
	// 	'Transaction' => 'Transaction', //Relation Language=english, Type=text, Content=content
	// 	'Proposal' => 'Proposal', //Type=type, Content=content
	// 	'Report' => 'Report', //Type=type, Content=content
	// 	'Tags' => 'Tags' //Comma separated
	// );

	// public $relationCallbacks = array(
	// 	'Organisation.Title' => array(
	// 		 'relationname' => 'Organisation',
	// 		 'callback' => 'getOrganisationByTitle'
	// 	),
	// 	'OrganisationType.Title' => array(
	// 		 'relationname' => 'OrganisationType',
	// 		 'callback' => 'getOrganisationTypeByTitle'
	// 	),
	// 	'Status.Title' => array(
	// 		 'relationname' => 'Status',
	// 		 'callback' => 'getStatusByTitle'
	// 	),
	// 	'Region.Title' => array(
	// 		 'relationname' => 'Region',
	// 		 'callback' => 'getRegionByTitle'
	// 	),
	// 	'TLA.Title' => array(
	// 		 'relationname' => 'TLA',
	// 		 'callback' => 'getTLAByTitle'
	// 	)
	// );

	// public static function getOrganisationByTitle(&$obj, $val, $record) {
	// 	$org = GrantOrganisation::get()->filter('Title', $val);
	// 	if($org->Count() < 1){
	// 		$newOrg = new GrantOrganisation();
	// 		$newOrg->Title = $val;
	// 		$newOrg->write();
	// 		return $newOrg;
	// 	} else {
	// 		return $org->First();
	// 	}
	// }
	// public static function getOrganisationTypeByTitle(&$obj, $val, $record) {
	// 	$type = GrantOrganisationType::get()->filter('Title', $val);
	// 	if($type->Count() < 1){
	// 		$newType = new GrantOrganisationType();
	// 		$newType->Title = $val;
	// 		$newType->write();
	// 		return $newType;
	// 	} else {
	// 		return $type->First();
	// 	}
	// }

	// public static function getStatusByTitle(&$obj, $val, $record) {
	// 	$sta = GrantStatus::get()->filter('Title', $val);
	// 	if($sta->Count() < 1 && $val != null){

	// 		$newSta = new GrantStatus();
	// 		$newSta->Title = $val;
	// 		$newSta->write();
	// 		return $newSta;
	// 	} else {
	// 		return $sta->First();
	// 	}
	// }

	// public static function getRegionByTitle(&$obj, $val, $record) {
	// 	$reg = GrantRegion::get()->filter('Title', $val);
	// 	if($reg->Count() < 1){
	// 		$newReg = new GrantRegion();
	// 		$newReg->Title = $val;
	// 		$newReg->write();
	// 		return $newReg;
	// 	} else {
	// 		return $reg->First();
	// 	}
	// }

	// public static function getTLAByTitle(&$obj, $val, $record) {
	// 	$tla = GrantTLA::get()->filter('Title', $val);
	// 	if($tla->Count() < 1){
	// 		$newTla = new GrantTLA();
	// 		$newTla->Title = $val;
	// 		$newTla->write();
	// 		return $newTla;
	// 	} else {
	// 		return $tla->First();
	// 	}
	// }

	// //Overridden to include a callback for cleaning.
	// protected function processAll($filepath, $preview = false){
	// 	$results = parent::processAll($filepath, $preview);

	// 	$this->cleanRelations();

	// 	return $results;
	// }

	// /**
	// * Goes through all the newly created relations, deleting attribute objects that have no title and replaces the Relation ID with 0.
	// * These null value attributes are generated by empty cells in the imported CSV file.
	// */
	// public function cleanRelations(){
	// 	//TLA
	// 	$tlaCount = 0;
	// 	$objs = GrantTLA::get();
	// 	foreach($objs as $obj){
	// 		if($obj->Title == null){
	// 			$tlaCount++;
	// 			foreach($obj->Grants() as $grant){
	// 				$grant->TLAID = 0;
	// 				$grant->write();
	// 			}
	// 			$obj->delete();
	// 		}
	// 	}

	// 	//Organisation
	// 	$orgCount = 0;
	// 	$objs = GrantOrganisation::get();
	// 	foreach($objs as $obj){
	// 		if($obj->Title == null){
	// 			$orgCount++;
	// 			foreach($obj->Grants() as $grant){
	// 				$grant->OrganisationID = 0;
	// 				$grant->write();
	// 			}
	// 			$obj->delete();
	// 		}
	// 	}

	// 	//Organisation Types
	// 	$typeCount = 0;
	// 	$objs = GrantOrganisationType::get();
	// 	foreach($objs as $obj){
	// 		if($obj->Title == null){
	// 			$typeCount++;
	// 			foreach($obj->Grants() as $grant){
	// 				$grant->OrganisationTypeID = 0;
	// 				$grant->write();
	// 			}
	// 			$obj->delete();
	// 		}
	// 	}

	// 	//Regions
	// 	$regionCount = 0;
	// 	$objs = GrantRegion::get();
	// 	foreach($objs as $obj){
	// 		if($obj->Title == null){
	// 			$regionCount++;
	// 			foreach($obj->Grants() as $grant){
	// 				$grant->RegionID = 0;
	// 				$grant->write();
	// 			}
	// 			$obj->delete();
	// 		}
	// 	}

	// 	//Status
	// 	$statusCount = 0;
	// 	$objs = GrantStatus::get();
	// 	foreach($objs as $obj){
	// 		if($obj->Title == null){
	// 			$statusCount++;
	// 			foreach($obj->Grants() as $grant){
	// 				$grant->StatusID = 0;
	// 				$grant->write();
	// 			}
	// 			$obj->delete();
	// 		}
	// 	}
	// }


}